version: 2

jobs:
  create-project:
    docker:
      - image: circleci/python:3.9
    steps:
      - run:
          command: |
            pip install cookiecutter
            cookiecutter gh:prodinit/django-boilerplate --no-input project_name=dummy
            cd dummy
            rm -rf .github
            rm -rf deployment
            pip install poetry
            poetry install
            poetry run pytest --cov -v --tb=native

workflows:
  version: 2
  setup:
    jobs:
      - create-project
